Import('env', 'arch', 'common', 'messaging', 'visionipc', 'transformations')

base_libs = [common, messaging, visionipc, transformations,
             'm', 'ssl', 'crypto', 'pthread', 'flutter_linux']

if arch == 'larch64':
  base_libs.append('EGL')

# build main UI
env.Program("ui", ["agnos_flutter/main.cc", "flutter_bridge.cc", "device.cc"], LIBS=base_libs)
